# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build & Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    
    - name: Install Cuda
      run: sudo apt -y update && sudo apt -y install nvidia-cuda-toolkit-gcc nvidia-cudnn

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'

    - name: Build
      run: make setup.whisper
      working-directory: discord-bot
      env:
        CGO_LDFLAGS: "-L/opt/cuda/targets/x86_64-linux/lib/stubs/ -L/opt/cuda/lib64/ -lcuda -lcublas -lcudart -lculibos -lcublasLt"
        LDFLAGS: "-L/opt/cuda/targets/x86_64-linux/lib/stubs/ -L/opt/cuda/lib64/ -lcuda -lcublas -lcudart -lculibos -lcublasLt"
        WHISPER_CUDA: 1

    - name: Build
      run: make go.build
      working-directory: discord-bot
      env:
        C_INCLUDE_PATH: third_party/whisper.cpp/
        CGO_LDFLAGS: "-L/opt/cuda/targets/x86_64-linux/lib/stubs/ -L/opt/cuda/lib64/ -lcuda -lcublas -lcudart -lculibos -lcublasLt"
        LDFLAGS: "-L/opt/cuda/targets/x86_64-linux/lib/stubs/ -L/opt/cuda/lib64/ -lcuda -lcublas -lcudart -lculibos -lcublasLt"
        LIBRARY_PATH: third_party/whisper.cpp/

    - name: Test
      run: go test -v ./...
      working-directory: discord-bot
      env:
        C_INCLUDE_PATH: third_party/whisper.cpp/
        CGO_LDFLAGS: "-L/opt/cuda/targets/x86_64-linux/lib/stubs/ -L/opt/cuda/lib64/ -lcuda -lcublas -lcudart -lculibos -lcublasLt"
        LDFLAGS: "-L/opt/cuda/targets/x86_64-linux/lib/stubs/ -L/opt/cuda/lib64/ -lcuda -lcublas -lcudart -lculibos -lcublasLt"
        LIBRARY_PATH: third_party/whisper.cpp/
        STT_MODEL_PATH: third_party/whisper.cpp/bindings/go/models/ggml-large-v3.bin
